<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="de_DE">
<context>
    <name>DBError</name>
    <message>
        <location filename="dderror.py" line="34"/>
        <source>Database Error:</source>
        <translation>Datenbankfehler:</translation>
    </message>
</context>
<context>
    <name>DdError</name>
    <message>
        <location filename="ddui.py" line="43"/>
        <source>Layer is not a vector layer:</source>
        <translation>Folgender Layer is kein Vektorlayer:</translation>
    </message>
    <message>
        <location filename="ddui.py" line="48"/>
        <source>Layer is not a PostgreSQL layer:</source>
        <translation>Folgender Layer ist kein PostgreSQL-Layer:</translation>
    </message>
    <message>
        <location filename="ddui.py" line="62"/>
        <source>Layer is not a PostgreSQL table:</source>
        <translation>Folgender Layer ist keine PostgreSQL-Tabelle:</translation>
    </message>
    <message>
        <location filename="ddui.py" line="175"/>
        <source>Error starting transaction on DB </source>
        <translation>Fehler beim Starten einer Transaktion auf der DB</translation>
    </message>
    <message>
        <location filename="ddui.py" line="185"/>
        <source>Error rolling back transaction on DB </source>
        <translation>Fehler beim Rückgängigmachen der Transaktion auf der DB</translation>
    </message>
    <message>
        <location filename="ddui.py" line="190"/>
        <source>Error committing transaction on DB </source>
        <translation>Fehler beim Wegschreiben der Daten in die DB</translation>
    </message>
    <message>
        <location filename="ddui.py" line="274"/>
        <source>Could not connect to PostgreSQL database:</source>
        <translation>Konnte mich nicht mit folgender PostgreSQL-Datenbank verbinden:</translation>
    </message>
    <message>
        <location filename="ddui.py" line="1026"/>
        <source>Field not found in layer:</source>
        <translation>Das folgende Feld wurde im Layer nicht gefunden:</translation>
    </message>
    <message>
        <location filename="ddui.py" line="1674"/>
        <source>Could not save changes to layer:</source>
        <translation>Konnte Änderungen in folgendem Layer nicht speichern:</translation>
    </message>
    <message>
        <location filename="ddui.py" line="1683"/>
        <source>Could not discard changes for layer:</source>
        <translation>Konnte Änderungen in folgendem Layer nicht verwerfen:</translation>
    </message>
    <message>
        <location filename="datadriveninputmask.py" line="97"/>
        <source>No selection in layer:</source>
        <translation>Der folgende Layer enthält keine Selektion:</translation>
    </message>
</context>
<context>
    <name>DdInfo</name>
    <message>
        <location filename="ddui.py" line="1534"/>
        <source>n-to-m relation for new feature cannot be saved</source>
        <translation>Für ein neues Feature kann kein n-zu-m Eintrag gespeichert werden</translation>
    </message>
    <message>
        <location filename="ddui.py" line="1641"/>
        <source>Layer cannot be edited:</source>
        <translation>Der folgende Layer kann nicht editiert werden:</translation>
    </message>
    <message>
        <location filename="dddialog.py" line="48"/>
        <source>New Feature</source>
        <translation>Neues Feature</translation>
    </message>
    <message>
        <location filename="dddialog.py" line="51"/>
        <source>Feature</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>DdInput</name>
    <message>
        <location filename="ddui.py" line="1702"/>
        <source>Add</source>
        <translation>Neu</translation>
    </message>
    <message>
        <location filename="ddui.py" line="1704"/>
        <source>Remove</source>
        <translation>Löschen</translation>
    </message>
</context>
<context>
    <name>DdWarning</name>
    <message>
        <location filename="ddui.py" line="1127"/>
        <source>Input in Field is not a double according to local settings! </source>
        <translation>Ihre Eingabe in das Feld ist gemäß den lokalen Einstellungen kein Double-Wert!</translation>
    </message>
    <message>
        <location filename="ddui.py" line="1153"/>
        <source>Input in Field is too long! </source>
        <translation>Ihre Eingabe in das Feld ist zu lang!</translation>
    </message>
    <message>
        <location filename="ddui.py" line="1158"/>
        <source>Input in Field is too short!</source>
        <translation>Ihre Eingabe in das Feld ist zu kurz!</translation>
    </message>
    <message>
        <location filename="ddui.py" line="1013"/>
        <source>Field must not be empty!</source>
        <translation>Das Feld darf nicht leer sein!</translation>
    </message>
</context>
</TS>
